module "my_application"{
    source = "../../Modules/Application"
    profile = "${var.profile}"
    region = "${var.region}"
    vpc_id = "${var.vpc_id}"
    ami    ="${var.ami}"
    key_name="${var.key_name}"
    bucket_name = "${var.bucket_name}"
    database_identifier = "${var.database_identifier}"
    database_name = "${var.database_name}"
    database_username = "${var.database_username}"
    database_password = "${var.database_password}"
    instance_type = "${var.instance_type}"
    storage_type = "${var.storage_type}"
    allocated_storage = "${var.allocated_storage}"
    cd_bucket_name = "${var.cd_bucket_name}"
    TTL_DELAY = "${var.TTL_DELAY}"
    lambda_bucket_name = "${var.lambda_bucket_name}"
    ses_verified_domain = "${var.ses_verified_domain}"
    DOMAIN = "${var.DOMAIN}"
    SSLCertificateId="${var.SSLCertificateId}"
}
